version: 2
updates:
  # Maintain GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Monitor the main Workspace root
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"

  # Monitor Serverpod Backend
  - package-ecosystem: "pub"
    directory: "/gsdui_server/"
    schedule:
      interval: "weekly"

  # Monitor Client Library
  - package-ecosystem: "pub"
    directory: "/gsdui_client/"
    schedule:
      interval: "weekly"

  # Monitor Flutter Frontend
  - package-ecosystem: "pub"
    directory: "/gsdui_flutter/"
    schedule:
      interval: "weekly"

  # Monitor Docker images in the backend
  - package-ecosystem: "docker"
    directory: "/gsdui_server/"
    schedule:
      interval: "weekly"
