services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: gsdui
      POSTGRES_PASSWORD: "3SZREnQ_us3VYgVRgPpEptAUg8c9FPg6"
    volumes:
      - gsdui_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "3VPybD7_tUADylXoLZKDm8KNRGIPRnl4"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: gsdui_test
      POSTGRES_PASSWORD: "HsptsR9BkkW-yupjt_O-33BinWCtSwgt"
    volumes:
      - gsdui_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "PdNVuiSakCmlkkJ5WmYTq_vBOTILKnQ1"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  gsdui_data:
  gsdui_test_data:
